# Generated by Django 5.1.6 on 2025-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ward', models.PositiveIntegerField(choices=[(1, 'Ward 1'), (2, 'Ward 2'), (3, 'Ward 3'), (4, 'Ward 4'), (5, 'Ward 5'), (6, 'Ward 6'), (7, 'Ward 7'), (8, 'Ward 8'), (9, 'Ward 9'), (10, 'Ward 10'), (11, 'Ward 11'), (12, 'Ward 12'), (13, 'Ward 13'), (14, 'Ward 14'), (15, 'Ward 15'), (16, 'Ward 16'), (17, 'Ward 17'), (18, 'Ward 18'), (19, 'Ward 19'), (20, 'Ward 20'), (21, 'Ward 21'), (22, 'Ward 22'), (23, 'Ward 23'), (24, 'Ward 24'), (25, 'Ward 25'), (26, 'Ward 26'), (27, 'Ward 27'), (28, 'Ward 28'), (29, 'Ward 29'), (30, 'Ward 30'), (31, 'Ward 31'), (32, 'Ward 32'), (33, 'Ward 33'), (34, 'Ward 34'), (35, 'Ward 35')])),
                ('certificates', models.JSONField()),
                ('request_type', models.CharField(choices=[('emergency', 'Emergency'), ('normal', 'Normal')], max_length=20)),
            ],
        ),
    ]
