# Generated by Django 5.1.6 on 2025-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointmentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='iscomplete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
