# Generated by Django 5.1.6 on 2025-04-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_appointmentform_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='isschedule',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
